# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

## => Site Settings
##############################
text_skin: default
highlight_theme: default
url     : https://soon-project.eu
title   : SOON project

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: soon-project/soon-project.github.io
repository_tree: master

## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - /tools

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
